/**
 * gateway API
 * gateway API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Category } from './category';
import { Shop } from './shop';
import { Specs } from './specs';


/**
 * The Entity entity. @author A true hipster
 */
export interface Product { 
    category?: Category;
    description?: string;
    id?: number;
    /**
     * fieldName
     */
    name?: string;
    shop?: Shop;
    specs?: Array<Specs>;
    thumbnail?: string;
}
