/**
 * gateway API
 * gateway API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderDetails } from './orderDetails';
import { Shop } from './shop';


/**
 * The Entity entity. @author A true hipster
 */
export interface ShopOrder { 
    id?: number;
    orderDetails?: Array<OrderDetails>;
    /**
     * fieldName
     */
    orderNo?: string;
    shop?: Shop;
    totalMoney?: number;
}
