export * from './accountResource.service';
import { AccountResourceService } from './accountResource.service';
export * from './categoryResource.service';
import { CategoryResourceService } from './categoryResource.service';
export * from './customerResource.service';
import { CustomerResourceService } from './customerResource.service';
export * from './deskResource.service';
import { DeskResourceService } from './deskResource.service';
export * from './orderDetailsResource.service';
import { OrderDetailsResourceService } from './orderDetailsResource.service';
export * from './orderFormResource.service';
import { OrderFormResourceService } from './orderFormResource.service';
export * from './productResource.service';
import { ProductResourceService } from './productResource.service';
export * from './specsResource.service';
import { SpecsResourceService } from './specsResource.service';
export * from './storeResource.service';
import { StoreResourceService } from './storeResource.service';
export * from './unitResource.service';
import { UnitResourceService } from './unitResource.service';
export * from './userJwtController.service';
import { UserJwtControllerService } from './userJwtController.service';
export * from './userResource.service';
import { UserResourceService } from './userResource.service';
export * from './vipResource.service';
import { VipResourceService } from './vipResource.service';
export const APIS = [AccountResourceService, CategoryResourceService, CustomerResourceService, DeskResourceService, OrderDetailsResourceService, OrderFormResourceService, ProductResourceService, SpecsResourceService, StoreResourceService, UnitResourceService, UserJwtControllerService, UserResourceService, VipResourceService];
