/**
 * gateway API
 * gateway API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';


/**
 * The Entity entity. @author A true hipster
 */
export interface Specs { 
    id?: number;
    /**
     * fieldName
     */
    name?: string;
    price?: number;
    product?: Product;
    stock?: number;
}
