/**
 * gateway API
 * gateway API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';
import { Store } from './store';


/**
 * The 商品分类. @author A true hipster
 */
export interface Category { 
    id?: number;
    name?: string;
    products?: Array<Product>;
    sort?: number;
    store?: Store;
}
