/**
 * gateway API
 * gateway API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


/**
 * The 顾客. @author A true hipster
 */
export interface Customer { 
    id?: number;
    name?: string;
    telephone?: string;
    user?: User;
    /**
     * 微信unionid
     */
    wxUniond?: string;
}
