/**
 * gateway API
 * gateway API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Category } from './category';
import { Desk } from './desk';
import { OrderForm } from './orderForm';
import { Product } from './product';
import { User } from './user';
import { Vip } from './vip';


/**
 * The 商店. @author A true hipster
 */
export interface Store { 
    categories?: Array<Category>;
    description?: string;
    desks?: Array<Desk>;
    id?: number;
    name?: string;
    orderForms?: Array<OrderForm>;
    products?: Array<Product>;
    user?: User;
    vips?: Array<Vip>;
}
