/**
 * gateway API
 * gateway API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Category } from './category';
import { Product } from './product';
import { ShopOrder } from './shopOrder';
import { User } from './user';


/**
 * The Entity entity. @author A true hipster
 */
export interface Shop { 
    categories?: Array<Category>;
    id?: number;
    /**
     * fieldName
     */
    name?: string;
    products?: Array<Product>;
    shopOrders?: Array<ShopOrder>;
    user?: User;
}
